import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// CSV data embedded
const CATALOG_DATA = [
  ["fournitures_universel_fixations_chevilles_nylon_assorties_lot","Fournitures > Universel > Fixations","Chevilles nylon assorties (lot)","PETITE_FOURNITURE","lot",1,"fixation"],
  ["fournitures_universel_fixations_chevilles_chimiques_canule","Fournitures > Universel > Fixations","Chevilles chimiques + canule","PETITE_FOURNITURE","u",1,"fixation"],
  ["fournitures_universel_fixations_tiges_filet_es_m8_m10_assortiment","Fournitures > Universel > Fixations","Tiges filetées M8/M10 (assortiment)","PETITE_FOURNITURE","lot",1,"fixation"],
  ["fournitures_universel_fixations_vis_inox_assorties_lot","Fournitures > Universel > Fixations","Vis inox assorties (lot)","PETITE_FOURNITURE","lot",1,"fixation"],
  ["fournitures_universel_fixations_crous_rondelles_inox_lot","Fournitures > Universel > Fixations","Écrous/rondelles inox (lot)","PETITE_FOURNITURE","lot",1,"fixation"],
  ["fournitures_universel_fixations_colliers_de_fixation_pvc_32_100","Fournitures > Universel > Fixations","Colliers de fixation PVC Ø32-Ø100","PETITE_FOURNITURE","u",10,"collier"],
  ["fournitures_universel_fixations_colliers_isophoniques_12_28","Fournitures > Universel > Fixations","Colliers isophoniques Ø12-Ø28","PETITE_FOURNITURE","u",10,"collier"],
  ["fournitures_universel_fixations_colliers_cuivre_12_28","Fournitures > Universel > Fixations","Colliers cuivre Ø12-Ø28","PETITE_FOURNITURE","u",10,"collier"],
  ["fournitures_universel_fixations_saddles_colliers_per_multicouche","Fournitures > Universel > Fixations","Saddles/colliers PER/multicouche","PETITE_FOURNITURE","u",10,"collier"],
  ["fournitures_universel_joints_joints_plats_fibre_assortis","Fournitures > Universel > Joints","Joints plats fibre assortis","PETITE_FOURNITURE","lot",1,"joint"],
  ["fournitures_universel_joints_joints_toriques_assortis","Fournitures > Universel > Joints","Joints toriques assortis","PETITE_FOURNITURE","lot",1,"joint"],
  ["fournitures_universel_joints_joints_silicone_sanitaires_assortiment","Fournitures > Universel > Joints","Joints silicone sanitaires (assortiment)","PETITE_FOURNITURE","lot",1,"joint"],
  ["fournitures_universel_tanch_it_ruban_ptfe_t_flon","Fournitures > Universel > Étanchéité","Ruban PTFE (téflon)","CONSOMMABLE","u",1,"etancheite"],
  ["fournitures_universel_tanch_it_filasse","Fournitures > Universel > Étanchéité","Filasse","CONSOMMABLE","u",1,"etancheite"],
  ["fournitures_universel_tanch_it_p_te_d_tanch_it","Fournitures > Universel > Étanchéité","Pâte d'étanchéité","CONSOMMABLE","u",1,"etancheite"],
  ["fournitures_universel_tanch_it_silicone_sanitaire_anti_moisissure","Fournitures > Universel > Étanchéité","Silicone sanitaire anti-moisissure","CONSOMMABLE","u",1,"etancheite"],
  ["fournitures_universel_tanch_it_mastic_polym_re_multi_mat_riaux","Fournitures > Universel > Étanchéité","Mastic polymère (multi-matériaux)","CONSOMMABLE","u",1,"etancheite"],
  ["fournitures_universel_pvc_colle_pvc_pression_vacuation","Fournitures > Universel > PVC","Colle PVC pression/évacuation","CONSOMMABLE","u",1,"pvc"],
  ["fournitures_universel_pvc_d_capant_nettoyant_pvc","Fournitures > Universel > PVC","Décapant/nettoyant PVC","CONSOMMABLE","u",1,"pvc"],
  ["fournitures_universel_protection_chantier_b_ches_de_protection_rouleau","Fournitures > Universel > Protection chantier","Bâches de protection (rouleau)","CONSOMMABLE","u",1,"chantier"],
  ["fournitures_universel_protection_chantier_ruban_de_masquage","Fournitures > Universel > Protection chantier","Ruban de masquage","CONSOMMABLE","u",1,"chantier"],
  ["fournitures_universel_protection_chantier_sacs_gravats","Fournitures > Universel > Protection chantier","Sacs gravats","CONSOMMABLE","lot",1,"chantier"],
  ["fournitures_universel_divers_a_rateur_membrane_anti_odeur","Fournitures > Universel > Divers","Aérateur à membrane (anti-odeur)","PETITE_FOURNITURE","u",1,"ventilation"],
  ["fournitures_universel_divers_clapet_anti_retour_eu","Fournitures > Universel > Divers","Clapet anti-retour (EU)","PETITE_FOURNITURE","u",1,"evacuation"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","Sanitaire > WC","Pack WC posé (cuvette + réservoir)","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_cuvette_wc_pos_e_seule","Sanitaire > WC","Cuvette WC posée seule","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_r_servoir_wc_complet","Sanitaire > WC","Réservoir WC (complet)","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_m_canisme_de_chasse_simple","Sanitaire > WC","Mécanisme de chasse (simple)","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_m_canisme_de_chasse_double_d_bit","Sanitaire > WC","Mécanisme de chasse (double débit)","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_robinet_flotteur","Sanitaire > WC","Robinet flotteur","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_abattant_standard","Sanitaire > WC","Abattant standard","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_abattant_frein_de_chute","Sanitaire > WC","Abattant frein de chute","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_broyeur_wc","Sanitaire > WC","Broyeur WC","GROSSE_FOURNITURE","u",1,"wc"],
  ["sanitaire_wc_wc_suspendu_cuvette_wc_suspendue","Sanitaire > WC > WC suspendu","Cuvette WC suspendue","GROSSE_FOURNITURE","u",1,"wc_susp"],
  ["sanitaire_wc_wc_suspendu_b_ti_support_universel","Sanitaire > WC > WC suspendu","Bâti-support universel","GROSSE_FOURNITURE","u",1,"wc_susp"],
  ["sanitaire_wc_wc_suspendu_plaque_de_commande_double_touche","Sanitaire > WC > WC suspendu","Plaque de commande double touche","GROSSE_FOURNITURE","u",1,"wc_susp"],
  ["sanitaire_wc_petites_fournitures_pipe_wc_droite_100","Sanitaire > WC > Petites fournitures","Pipe WC droite Ø100","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_pipe_wc_coud_e_100","Sanitaire > WC > Petites fournitures","Pipe WC coudée Ø100","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_pipe_wc_extensible_100","Sanitaire > WC > Petites fournitures","Pipe WC extensible Ø100","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_manchon_wc_100_110","Sanitaire > WC > Petites fournitures","Manchon WC Ø100/110","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_r_duction_wc_90_100","Sanitaire > WC > Petites fournitures","Réduction WC Ø90/100","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_joint_de_pipe_wc","Sanitaire > WC > Petites fournitures","Joint de pipe WC","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_joint_cuvette_wc","Sanitaire > WC > Petites fournitures","Joint cuvette WC","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_robinet_d_arr_t_1_4_tour_12_17","Sanitaire > WC > Petites fournitures","Robinet d'arrêt 1/4 tour 12/17","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_flexible_alimentation_wc_12_17","Sanitaire > WC > Petites fournitures","Flexible alimentation WC 12/17","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_kit_fixation_cuvette_vis_tiges_chevilles","Sanitaire > WC > Petites fournitures","Kit fixation cuvette (vis/tiges/chevilles)","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_wc_petites_fournitures_kit_isolation_phonique_wc_suspendu","Sanitaire > WC > Petites fournitures","Kit isolation phonique WC suspendu","PETITE_FOURNITURE","u",1,"wc_pf"],
  ["sanitaire_lavabo_vasque_vier_vasque_poser","Sanitaire > Lavabo/Vasque/Évier","Vasque à poser","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_vasque_encastr_e","Sanitaire > Lavabo/Vasque/Évier","Vasque encastrée","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_lavabo","Sanitaire > Lavabo/Vasque/Évier","Lavabo","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","Sanitaire > Lavabo/Vasque/Évier","Évier 1 bac","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_vier_2_bacs","Sanitaire > Lavabo/Vasque/Évier","Évier 2 bacs","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_lavabo","Sanitaire > Lavabo/Vasque/Évier","Mitigeur lavabo","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_vier","Sanitaire > Lavabo/Vasque/Évier","Mitigeur évier","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_vier_avec_douchette","Sanitaire > Lavabo/Vasque/Évier","Mitigeur évier avec douchette","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_vidage_lavabo_bonde_tirette","Sanitaire > Lavabo/Vasque/Évier","Vidage lavabo (bonde + tirette)","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_vidage_vier_bonde_panier","Sanitaire > Lavabo/Vasque/Évier","Vidage évier (bonde panier)","GROSSE_FOURNITURE","u",1,"sanitaire"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_siphon_lavabo_32","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Siphon lavabo Ø32","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_siphon_vier_40_1_bac","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Siphon évier Ø40 (1 bac)","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_siphon_vier_40_2_bacs","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Siphon évier Ø40 (2 bacs)","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_tube_pvc_vacuation_32_1_m","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Tube PVC évacuation Ø32 (1 m)","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_tube_pvc_vacuation_40_1_m","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Tube PVC évacuation Ø40 (1 m)","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_coude_pvc_32_87","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Coude PVC Ø32 87°","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_coude_pvc_40_87","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Coude PVC Ø40 87°","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_manchon_pvc_32","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Manchon PVC Ø32","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_manchon_pvc_40","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Manchon PVC Ø40","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_t_pvc_40","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Té PVC Ø40","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_r_duction_pvc_40_32","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Réduction PVC Ø40/32","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_rosace_murale","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Rosace murale","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_flexibles_alimentation_3_8_pair","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Flexibles alimentation 3/8 (paire)","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_robinets_d_arr_t_1_4_tour_12_17","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Robinets d'arrêt 1/4 tour 12/17 (paire)","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_lavabo_vasque_vier_petites_fournitures_joint_siphon_bonde_lot","Sanitaire > Lavabo/Vasque/Évier > Petites fournitures","Joint siphon/bonde (lot)","PETITE_FOURNITURE","u",1,"evier_pf"],
  ["sanitaire_douche_baignoire_mitigeur_douche_mural","Sanitaire > Douche/Baignoire","Mitigeur douche mural","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_mitigeur_baignoire_mural","Sanitaire > Douche/Baignoire","Mitigeur baignoire mural","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_colonne_de_douche","Sanitaire > Douche/Baignoire","Colonne de douche","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_ensemble_douchette_flexible_support","Sanitaire > Douche/Baignoire","Ensemble douchette + flexible + support","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_receveur_de_douche","Sanitaire > Douche/Baignoire","Receveur de douche","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_paroi_de_douche","Sanitaire > Douche/Baignoire","Paroi de douche","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_bonde_de_douche","Sanitaire > Douche/Baignoire","Bonde de douche","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_siphon_extra_plat","Sanitaire > Douche/Baignoire","Siphon extra-plat","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_caniveau_de_douche","Sanitaire > Douche/Baignoire","Caniveau de douche","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_vidage_baignoire_complet","Sanitaire > Douche/Baignoire","Vidage baignoire (complet)","GROSSE_FOURNITURE","u",1,"douche"],
  ["sanitaire_douche_baignoire_petites_fournitures_raccords_excentr_s_paire","Sanitaire > Douche/Baignoire > Petites fournitures","Raccords excentrés (paire)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_rosaces_paire","Sanitaire > Douche/Baignoire > Petites fournitures","Rosaces (paire)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_flexible_douche_inox_1_5m","Sanitaire > Douche/Baignoire > Petites fournitures","Flexible douche inox 1,5m","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_flexible_douche_inox_2m","Sanitaire > Douche/Baignoire > Petites fournitures","Flexible douche inox 2m","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_cartouche_mitigeur_universelle","Sanitaire > Douche/Baignoire > Petites fournitures","Cartouche mitigeur (universelle)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_clapets_anti_retour_paire","Sanitaire > Douche/Baignoire > Petites fournitures","Clapets anti-retour (paire)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_tube_pvc_vacuation_40_1_m","Sanitaire > Douche/Baignoire > Petites fournitures","Tube PVC évacuation Ø40 (1 m)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_tube_pvc_vacuation_50_1_m","Sanitaire > Douche/Baignoire > Petites fournitures","Tube PVC évacuation Ø50 (1 m)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_coude_pvc_40_45","Sanitaire > Douche/Baignoire > Petites fournitures","Coude PVC Ø40 45°","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_coude_pvc_50_45","Sanitaire > Douche/Baignoire > Petites fournitures","Coude PVC Ø50 45°","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_manchon_pvc_50","Sanitaire > Douche/Baignoire > Petites fournitures","Manchon PVC Ø50","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_colliers_40_50_lot","Sanitaire > Douche/Baignoire > Petites fournitures","Colliers Ø40/50 (lot)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["sanitaire_douche_baignoire_petites_fournitures_kit_tanch_it_bande_membrane_lot","Sanitaire > Douche/Baignoire > Petites fournitures","Kit étanchéité bande/membrane (lot)","PETITE_FOURNITURE","u",1,"douche_pf"],
  ["plomberie_alimentation_per_tube_per_12x16_couronne","Plomberie > Alimentation > PER","Tube PER 12x16 (couronne)","GROSSE_FOURNITURE","m",25,"per"],
  ["plomberie_alimentation_per_tube_per_16x20_couronne","Plomberie > Alimentation > PER","Tube PER 16x20 (couronne)","GROSSE_FOURNITURE","m",25,"per"],
  ["plomberie_alimentation_per_tube_per_20x25_couronne","Plomberie > Alimentation > PER","Tube PER 20x25 (couronne)","GROSSE_FOURNITURE","m",25,"per"],
  ["plomberie_alimentation_per_tube_per_25x32_couronne","Plomberie > Alimentation > PER","Tube PER 25x32 (couronne)","GROSSE_FOURNITURE","m",25,"per"],
  ["plomberie_alimentation_multicouche_tube_multicouche_16x2_couronne","Plomberie > Alimentation > Multicouche","Tube multicouche 16x2 (couronne)","GROSSE_FOURNITURE","m",25,"multicouche"],
  ["plomberie_alimentation_multicouche_tube_multicouche_20x2_couronne","Plomberie > Alimentation > Multicouche","Tube multicouche 20x2 (couronne)","GROSSE_FOURNITURE","m",25,"multicouche"],
  ["plomberie_alimentation_multicouche_tube_multicouche_26x3_couronne","Plomberie > Alimentation > Multicouche","Tube multicouche 26x3 (couronne)","GROSSE_FOURNITURE","m",25,"multicouche"],
  ["plomberie_alimentation_multicouche_tube_multicouche_32x3_couronne","Plomberie > Alimentation > Multicouche","Tube multicouche 32x3 (couronne)","GROSSE_FOURNITURE","m",25,"multicouche"],
  ["plomberie_alimentation_cuivre_tube_cuivre_12_barre","Plomberie > Alimentation > Cuivre","Tube cuivre Ø12 (barre)","GROSSE_FOURNITURE","m",5,"cuivre"],
  ["plomberie_alimentation_cuivre_tube_cuivre_14_barre","Plomberie > Alimentation > Cuivre","Tube cuivre Ø14 (barre)","GROSSE_FOURNITURE","m",5,"cuivre"],
  ["plomberie_alimentation_cuivre_tube_cuivre_16_barre","Plomberie > Alimentation > Cuivre","Tube cuivre Ø16 (barre)","GROSSE_FOURNITURE","m",5,"cuivre"],
  ["plomberie_alimentation_cuivre_tube_cuivre_18_barre","Plomberie > Alimentation > Cuivre","Tube cuivre Ø18 (barre)","GROSSE_FOURNITURE","m",5,"cuivre"],
  ["plomberie_alimentation_cuivre_tube_cuivre_22_barre","Plomberie > Alimentation > Cuivre","Tube cuivre Ø22 (barre)","GROSSE_FOURNITURE","m",5,"cuivre"],
  ["plomberie_alimentation_cuivre_tube_cuivre_28_barre","Plomberie > Alimentation > Cuivre","Tube cuivre Ø28 (barre)","GROSSE_FOURNITURE","m",5,"cuivre"],
  ["plomberie_alimentation_laiton_raccord_laiton_droit_m_f_12_17","Plomberie > Alimentation > Laiton","Raccord laiton droit M/F 12/17","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_laiton_raccord_laiton_r_duction_m_f_assortiment","Plomberie > Alimentation > Laiton","Raccord laiton réduction M/F (assortiment)","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_laiton_union_laiton_12_17","Plomberie > Alimentation > Laiton","Union laiton 12/17","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_laiton_raccord_di_lectrique_12_17","Plomberie > Alimentation > Laiton","Raccord diélectrique 12/17","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_12_17","Plomberie > Alimentation > Vannes","Vanne d'arrêt 1/4 tour 12/17","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_20_27","Plomberie > Alimentation > Vannes","Vanne d'arrêt 1/4 tour 20/27","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_vannes_vanne_sph_re_pleine_passage_26_34","Plomberie > Alimentation > Vannes","Vanne à sphère pleine passage 26/34","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_s_curit_clapet_anti_retour_ea","Plomberie > Alimentation > Sécurité","Clapet anti-retour EA","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_mesure_manom_tre_0_10_bar","Plomberie > Alimentation > Mesure","Manomètre 0-10 bar","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_mesure_r_ducteur_de_pression_r_glable","Plomberie > Alimentation > Mesure","Réducteur de pression réglable","GROSSE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_filtration_filtre_anti_impuret_s_bol","Plomberie > Alimentation > Filtration","Filtre anti-impuretés + bol","GROSSE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_filtration_cartouche_filtre_recharge","Plomberie > Alimentation > Filtration","Cartouche filtre (recharge)","PETITE_FOURNITURE","u",1,"alimentation"],
  ["plomberie_alimentation_per_raccords_manchon_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Manchon PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_coude_90_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Coude 90° PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_t_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Té PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_raccord_m_le_12_17_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Raccord mâle 12/17 PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_raccord_femelle_12_17_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Raccord femelle 12/17 PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_sortie_de_cloison_12_17_per_assortiment_selo","Plomberie > Alimentation > PER > Raccords","Sortie de cloison 12/17 PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_nourrice_2_d_parts_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Nourrice 2 départs PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_nourrice_3_d_parts_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Nourrice 3 départs PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_per_raccords_nourrice_4_d_parts_per_assortiment_selon","Plomberie > Alimentation > PER > Raccords","Nourrice 4 départs PER (assortiment/selon Ø)","PETITE_FOURNITURE","u",1,"per"],
  ["plomberie_alimentation_multicouche_raccords_manchon_multicouche_sertir_selon","Plomberie > Alimentation > Multicouche > Raccords","Manchon multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_coude_90_multicouche_sertir_selon","Plomberie > Alimentation > Multicouche > Raccords","Coude 90° multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_t_multicouche_sertir_selon","Plomberie > Alimentation > Multicouche > Raccords","Té multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_raccord_m_le_12_17_multicouche_serti","Plomberie > Alimentation > Multicouche > Raccords","Raccord mâle 12/17 multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_raccord_femelle_12_17_multicouche_se","Plomberie > Alimentation > Multicouche > Raccords","Raccord femelle 12/17 multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_sortie_de_cloison_12_17_multicouche_","Plomberie > Alimentation > Multicouche > Raccords","Sortie de cloison 12/17 multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_platine_double_sortie_multicouche_se","Plomberie > Alimentation > Multicouche > Raccords","Platine double sortie multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_nourrice_2_d_parts_multicouche_serti","Plomberie > Alimentation > Multicouche > Raccords","Nourrice 2 départs multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_multicouche_raccords_nourrice_4_d_parts_multicouche_serti","Plomberie > Alimentation > Multicouche > Raccords","Nourrice 4 départs multicouche à sertir (selon Ø)","PETITE_FOURNITURE","u",1,"multicouche"],
  ["plomberie_alimentation_cuivre_raccords_manchon_souder_selon","Plomberie > Alimentation > Cuivre > Raccords","Manchon à souder (selon Ø)","PETITE_FOURNITURE","u",1,"cuivre"],
  ["plomberie_alimentation_cuivre_raccords_coude_90_souder_selon","Plomberie > Alimentation > Cuivre > Raccords","Coude 90° à souder (selon Ø)","PETITE_FOURNITURE","u",1,"cuivre"],
  ["plomberie_alimentation_cuivre_raccords_t_souder_selon","Plomberie > Alimentation > Cuivre > Raccords","Té à souder (selon Ø)","PETITE_FOURNITURE","u",1,"cuivre"],
  ["plomberie_alimentation_cuivre_raccords_r_duction_souder_selon","Plomberie > Alimentation > Cuivre > Raccords","Réduction à souder (selon Ø)","PETITE_FOURNITURE","u",1,"cuivre"],
  ["plomberie_alimentation_cuivre_raccords_raccord_bic_ne_12_17_selon","Plomberie > Alimentation > Cuivre > Raccords","Raccord bicône 12/17 (selon Ø)","PETITE_FOURNITURE","u",1,"cuivre"],
  ["plomberie_alimentation_cuivre_raccords_raccord_olive_12_17_selon","Plomberie > Alimentation > Cuivre > Raccords","Raccord olive 12/17 (selon Ø)","PETITE_FOURNITURE","u",1,"cuivre"],
  ["plomberie_vacuation_pvc_tube_pvc_vacuation_32_1_m","Plomberie > Évacuation > PVC","Tube PVC évacuation Ø32 (1 m)","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_coude_45_pvc_32","Plomberie > Évacuation > PVC","Coude 45° PVC Ø32","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_coude_87_pvc_32","Plomberie > Évacuation > PVC","Coude 87° PVC Ø32","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_t_87_pvc_32","Plomberie > Évacuation > PVC","Té 87° PVC Ø32","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_culotte_45_pvc_32","Plomberie > Évacuation > PVC","Culotte 45° PVC Ø32","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_manchon_pvc_32","Plomberie > Évacuation > PVC","Manchon PVC Ø32","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_r_duction_pvc_32","Plomberie > Évacuation > PVC","Réduction PVC Ø32","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_tampon_de_visite_pvc_32","Plomberie > Évacuation > PVC","Tampon de visite PVC Ø32","PETITE_FOURNITURE","u",1,"pvc_ø32"],
  ["plomberie_vacuation_pvc_tube_pvc_vacuation_40_1_m","Plomberie > Évacuation > PVC","Tube PVC évacuation Ø40 (1 m)","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_coude_45_pvc_40","Plomberie > Évacuation > PVC","Coude 45° PVC Ø40","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_coude_87_pvc_40","Plomberie > Évacuation > PVC","Coude 87° PVC Ø40","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_t_87_pvc_40","Plomberie > Évacuation > PVC","Té 87° PVC Ø40","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_culotte_45_pvc_40","Plomberie > Évacuation > PVC","Culotte 45° PVC Ø40","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_manchon_pvc_40","Plomberie > Évacuation > PVC","Manchon PVC Ø40","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_r_duction_pvc_40","Plomberie > Évacuation > PVC","Réduction PVC Ø40","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_tampon_de_visite_pvc_40","Plomberie > Évacuation > PVC","Tampon de visite PVC Ø40","PETITE_FOURNITURE","u",1,"pvc_ø40"],
  ["plomberie_vacuation_pvc_tube_pvc_vacuation_50_1_m","Plomberie > Évacuation > PVC","Tube PVC évacuation Ø50 (1 m)","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_coude_45_pvc_50","Plomberie > Évacuation > PVC","Coude 45° PVC Ø50","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_coude_87_pvc_50","Plomberie > Évacuation > PVC","Coude 87° PVC Ø50","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_t_87_pvc_50","Plomberie > Évacuation > PVC","Té 87° PVC Ø50","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_culotte_45_pvc_50","Plomberie > Évacuation > PVC","Culotte 45° PVC Ø50","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_manchon_pvc_50","Plomberie > Évacuation > PVC","Manchon PVC Ø50","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_r_duction_pvc_50","Plomberie > Évacuation > PVC","Réduction PVC Ø50","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_tampon_de_visite_pvc_50","Plomberie > Évacuation > PVC","Tampon de visite PVC Ø50","PETITE_FOURNITURE","u",1,"pvc_ø50"],
  ["plomberie_vacuation_pvc_tube_pvc_vacuation_75_1_m","Plomberie > Évacuation > PVC","Tube PVC évacuation Ø75 (1 m)","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_coude_45_pvc_75","Plomberie > Évacuation > PVC","Coude 45° PVC Ø75","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_coude_87_pvc_75","Plomberie > Évacuation > PVC","Coude 87° PVC Ø75","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_t_87_pvc_75","Plomberie > Évacuation > PVC","Té 87° PVC Ø75","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_culotte_45_pvc_75","Plomberie > Évacuation > PVC","Culotte 45° PVC Ø75","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_manchon_pvc_75","Plomberie > Évacuation > PVC","Manchon PVC Ø75","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_r_duction_pvc_75","Plomberie > Évacuation > PVC","Réduction PVC Ø75","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_tampon_de_visite_pvc_75","Plomberie > Évacuation > PVC","Tampon de visite PVC Ø75","PETITE_FOURNITURE","u",1,"pvc_ø75"],
  ["plomberie_vacuation_pvc_tube_pvc_vacuation_100_1_m","Plomberie > Évacuation > PVC","Tube PVC évacuation Ø100 (1 m)","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_pvc_coude_45_pvc_100","Plomberie > Évacuation > PVC","Coude 45° PVC Ø100","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_pvc_coude_87_pvc_100","Plomberie > Évacuation > PVC","Coude 87° PVC Ø100","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_pvc_t_87_pvc_100","Plomberie > Évacuation > PVC","Té 87° PVC Ø100","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_pvc_culotte_45_pvc_100","Plomberie > Évacuation > PVC","Culotte 45° PVC Ø100","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_pvc_manchon_pvc_100","Plomberie > Évacuation > PVC","Manchon PVC Ø100","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_pvc_r_duction_pvc_100","Plomberie > Évacuation > PVC","Réduction PVC Ø100","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_pvc_tampon_de_visite_pvc_100","Plomberie > Évacuation > PVC","Tampon de visite PVC Ø100","PETITE_FOURNITURE","u",1,"pvc_ø100"],
  ["plomberie_vacuation_divers_siphon_de_sol","Plomberie > Évacuation > Divers","Siphon de sol","GROSSE_FOURNITURE","u",1,"evac"],
  ["plomberie_vacuation_divers_pompe_de_relevage_eaux_us_es","Plomberie > Évacuation > Divers","Pompe de relevage eaux usées","GROSSE_FOURNITURE","u",1,"evac"],
  ["plomberie_vacuation_divers_tuyau_souple_vacuation_machine_19_22","Plomberie > Évacuation > Divers","Tuyau souple évacuation (machine) 19/22","PETITE_FOURNITURE","u",1,"evac"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","Chauffage/ECS > Eau chaude > Chauffe-eau","Chauffe-eau électrique 50L","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","Chauffage/ECS > Eau chaude > Chauffe-eau","Chauffe-eau électrique 100L","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","Chauffage/ECS > Eau chaude > Chauffe-eau","Chauffe-eau électrique 150L","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","Chauffage/ECS > Eau chaude > Chauffe-eau","Chauffe-eau électrique 200L","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","Chauffage/ECS > Eau chaude > Chauffe-eau","Chauffe-eau électrique 300L","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","Chauffage/ECS > Eau chaude > Chauffe-eau","Chauffe-eau thermodynamique","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_ballon_tampon_chauffage","Chauffage/ECS > Eau chaude > Chauffe-eau","Ballon tampon (chauffage)","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_vase_d_expansion_sanitaire","Chauffage/ECS > Eau chaude > Chauffe-eau","Vase d'expansion sanitaire","GROSSE_FOURNITURE","u",1,"ecs"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_groupe_de_s_curit_20_27","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Groupe de sécurité 20/27","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_siphon_groupe_de_s_curi","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Siphon groupe de sécurité","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_raccord_di_lectriqu","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Kit raccord diélectrique (paire)","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_thermostat_chauffe_eau","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Thermostat chauffe-eau","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_r_sistance_st_atite","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Résistance stéatite","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_r_sistance_blind_e","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Résistance blindée","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_anode_magn_sium_aci","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Anode magnésium/ACI","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_fixation_chauffe_ea","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Kit fixation chauffe-eau (rails/équerres)","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_mitigeur_thermostatique","Chauffage/ECS > Eau chaude > Chauffe-eau > Petites fournitures","Mitigeur thermostatique anti-brûlure","PETITE_FOURNITURE","u",1,"ecs_pf"],
  ["chauffage_ecs_chauffage_radiateur_acier_panneau","Chauffage/ECS > Chauffage","Radiateur acier panneau","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_radiateur_s_che_serviettes","Chauffage/ECS > Chauffage","Radiateur sèche-serviettes","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_radiateur_fonte_section","Chauffage/ECS > Chauffage","Radiateur fonte (section)","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_convecteur_lectrique","Chauffage/ECS > Chauffage","Convecteur électrique","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_chaudi_re_gaz_murale_si_inclus","Chauffage/ECS > Chauffage","Chaudière gaz murale (si inclus)","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_pompe_chaleur_air_eau","Chauffage/ECS > Chauffage","Pompe à chaleur air/eau","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_circulateur_chauffage","Chauffage/ECS > Chauffage","Circulateur chauffage","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_vase_d_expansion_chauffage","Chauffage/ECS > Chauffage","Vase d'expansion chauffage","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_soupape_de_s_curit_chauffage_3_bar","Chauffage/ECS > Chauffage","Soupape de sécurité chauffage 3 bar","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_purgeur_automatique","Chauffage/ECS > Chauffage","Purgeur automatique","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_vanne_3_voies","Chauffage/ECS > Chauffage","Vanne 3 voies","GROSSE_FOURNITURE","u",1,"chauffage"],
  ["chauffage_ecs_chauffage_petites_fournitures_robinet_thermostatique","Chauffage/ECS > Chauffage > Petites fournitures","Robinet thermostatique","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_t_te_thermostatique","Chauffage/ECS > Chauffage > Petites fournitures","Tête thermostatique","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_t_de_r_glage","Chauffage/ECS > Chauffage > Petites fournitures","Té de réglage","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_purgeur_radiateur","Chauffage/ECS > Chauffage > Petites fournitures","Purgeur radiateur","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_support_radiateur_kit","Chauffage/ECS > Chauffage > Petites fournitures","Support radiateur (kit)","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_collecteur_plancher_chauffant","Chauffage/ECS > Chauffage > Petites fournitures","Collecteur plancher chauffant","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_d_bitm_tres_collecteur","Chauffage/ECS > Chauffage > Petites fournitures","Débitmètres collecteur","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_vannes_collecteur","Chauffage/ECS > Chauffage > Petites fournitures","Vannes collecteur","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_raccords_per_plancher_chauffant","Chauffage/ECS > Chauffage > Petites fournitures","Raccords PER plancher chauffant","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_isolant_plancher_chauffant_m","Chauffage/ECS > Chauffage > Petites fournitures","Isolant plancher chauffant (m²)","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_petites_fournitures_bande_p_riph_rique_rouleau","Chauffage/ECS > Chauffage > Petites fournitures","Bande périphérique (rouleau)","PETITE_FOURNITURE","u",1,"chauffage_pf"],
  ["chauffage_ecs_chauffage_consommables_produit_inhibiteur_corrosion_bidon","Chauffage/ECS > Chauffage > Consommables","Produit inhibiteur corrosion (bidon)","CONSOMMABLE","u",1,"chimie"],
  ["chauffage_ecs_chauffage_consommables_produit_d_sembouage_bidon","Chauffage/ECS > Chauffage > Consommables","Produit désembouage (bidon)","CONSOMMABLE","u",1,"chimie"],
  ["chauffage_ecs_chauffage_consommables_liquide_caloporteur_glycol","Chauffage/ECS > Chauffage > Consommables","Liquide caloporteur (glycol)","CONSOMMABLE","u",1,"chimie"],
  ["clim_ventilation_climatisation_climatiseur_split_mural_unit_int_rieure","Clim/Ventilation > Climatisation","Climatiseur split mural (unité intérieure)","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_unit_ext_rieure_clim_groupe","Clim/Ventilation > Climatisation","Unité extérieure clim (groupe)","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","Clim/Ventilation > Climatisation","Kit monosplit complet","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_kit_multisplit_complet","Clim/Ventilation > Climatisation","Kit multisplit complet","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_climatisation_gainable_unit","Clim/Ventilation > Climatisation","Climatisation gainable (unité)","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_pompe_de_relevage_condensats","Clim/Ventilation > Climatisation","Pompe de relevage condensats","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_thermostat_commande_filaire","Clim/Ventilation > Climatisation","Thermostat/commande filaire","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_t_l_commande_ir_remplacement","Clim/Ventilation > Climatisation","Télécommande IR (remplacement)","GROSSE_FOURNITURE","u",1,"clim"],
  ["clim_ventilation_climatisation_petites_fournitures_liaison_frigorifique_cuivre_i","Clim/Ventilation > Climatisation > Petites fournitures","Liaison frigorifique (cuivre isolé) 1/4-3/8 (m)","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_liaison_frigorifique_1_4_1_2_","Clim/Ventilation > Climatisation > Petites fournitures","Liaison frigorifique 1/4-1/2 (m)","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_goulotte_clim_accessoires","Clim/Ventilation > Climatisation > Petites fournitures","Goulotte clim + accessoires","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_support_mural_unit_ext_rieure","Clim/Ventilation > Climatisation > Petites fournitures","Support mural unité extérieure","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_plots_antivibratoires_lot","Clim/Ventilation > Climatisation > Petites fournitures","Plots antivibratoires (lot)","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_tuyau_vacuation_condensats_m","Clim/Ventilation > Climatisation > Petites fournitures","Tuyau évacuation condensats (m)","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_siphon_condensats","Clim/Ventilation > Climatisation > Petites fournitures","Siphon condensats","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_c_ble_lectrique_clim_m","Clim/Ventilation > Climatisation > Petites fournitures","Câble électrique clim (m)","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_disjoncteur_d_di_clim","Clim/Ventilation > Climatisation > Petites fournitures","Disjoncteur dédié clim","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_raccords_flare_lot","Clim/Ventilation > Climatisation > Petites fournitures","Raccords flare (lot)","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_bouchons_isolants_extr_mit_s","Clim/Ventilation > Climatisation > Petites fournitures","Bouchons/isolants extrémités","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_petites_fournitures_ruban_isolant_adh_sif_alu","Clim/Ventilation > Climatisation > Petites fournitures","Ruban isolant + adhésif alu","PETITE_FOURNITURE","u",1,"clim_pf"],
  ["clim_ventilation_climatisation_consommables_azote_test_tanch_it","Clim/Ventilation > Climatisation > Consommables","Azote (test étanchéité)","CONSOMMABLE","u",1,"clim_conso"],
  ["clim_ventilation_climatisation_consommables_gaz_r32_charge","Clim/Ventilation > Climatisation > Consommables","Gaz R32 (charge)","CONSOMMABLE","u",1,"clim_conso"],
  ["clim_ventilation_climatisation_consommables_gaz_r410a_charge","Clim/Ventilation > Climatisation > Consommables","Gaz R410A (charge)","CONSOMMABLE","u",1,"clim_conso"],
  ["clim_ventilation_climatisation_consommables_nettoyant_changeur_spray","Clim/Ventilation > Climatisation > Consommables","Nettoyant échangeur (spray)","CONSOMMABLE","u",1,"clim_conso"],
  ["clim_ventilation_climatisation_consommables_d_sinfectant_unit_int_rieure","Clim/Ventilation > Climatisation > Consommables","Désinfectant unité intérieure","CONSOMMABLE","u",1,"clim_conso"],
  ["clim_ventilation_climatisation_consommables_mousse_nettoyante_filtres","Clim/Ventilation > Climatisation > Consommables","Mousse nettoyante filtres","CONSOMMABLE","u",1,"clim_conso"],
  ["clim_ventilation_ventilation_vmc_vmc_simple_flux_groupe","Clim/Ventilation > Ventilation/VMC","VMC simple flux (groupe)","GROSSE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_vmc_hygror_glable_groupe","Clim/Ventilation > Ventilation/VMC","VMC hygroréglable (groupe)","GROSSE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_vmc_double_flux_groupe","Clim/Ventilation > Ventilation/VMC","VMC double flux (groupe)","GROSSE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_bouches_vmc_cuisine","Clim/Ventilation > Ventilation/VMC","Bouches VMC cuisine","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_bouches_vmc_sdb","Clim/Ventilation > Ventilation/VMC","Bouches VMC SDB","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_bouches_vmc_wc","Clim/Ventilation > Ventilation/VMC","Bouches VMC WC","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_gaines_vmc_isol_es_m","Clim/Ventilation > Ventilation/VMC","Gaines VMC isolées (m)","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_manchons_liaisons_gaine","Clim/Ventilation > Ventilation/VMC","Manchons/liaisons gaine","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_colliers_de_serrage_vmc","Clim/Ventilation > Ventilation/VMC","Colliers de serrage VMC","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_silencieux_vmc","Clim/Ventilation > Ventilation/VMC","Silencieux VMC","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_sortie_de_toit_chapeau","Clim/Ventilation > Ventilation/VMC","Sortie de toit/Chapeau","PETITE_FOURNITURE","u",1,"vmc"],
  ["clim_ventilation_ventilation_vmc_clapet_anti_retour_vmc","Clim/Ventilation > Ventilation/VMC","Clapet anti-retour VMC","PETITE_FOURNITURE","u",1,"vmc"],
  ["outillage_consommables_disque_diamant_carrelage","Outillage > Consommables","Disque diamant carrelage","OUTILLAGE_CONSO","u",1,"outil"],
  ["outillage_consommables_m_che_b_ton_6_12_assortiment","Outillage > Consommables","Mèche béton Ø6-Ø12 (assortiment)","OUTILLAGE_CONSO","u",1,"outil"],
  ["outillage_consommables_papier_abrasif","Outillage > Consommables","Papier abrasif","OUTILLAGE_CONSO","u",1,"outil"],
  ["outillage_consommables_lames_scie_sabre_lot","Outillage > Consommables","Lames scie sabre (lot)","OUTILLAGE_CONSO","u",1,"outil"],
  ["outillage_consommables_gaz_map_brasage_cartouche","Outillage > Consommables","Gaz MAP/brasage (cartouche)","OUTILLAGE_CONSO","u",1,"outil"],
  ["outillage_consommables_baguettes_brasure_cuivre","Outillage > Consommables","Baguettes/brasure cuivre","OUTILLAGE_CONSO","u",1,"outil"],
  ["outillage_consommables_d_capant_brasage","Outillage > Consommables","Décapant brasage","OUTILLAGE_CONSO","u",1,"outil"],
  ["outillage_consommables_gants_nitrile_bo_te","Outillage > Consommables","Gants nitrile (boîte)","OUTILLAGE_CONSO","u",1,"outil"],
  ["sanitaire_autres_autre_quipement_sanitaire_pr_ciser","Sanitaire > Autres","Autre équipement sanitaire (à préciser)","GROSSE_FOURNITURE","u",1,"autre"],
  ["plomberie_autres_autre_mat_riel_plomberie_pr_ciser","Plomberie > Autres","Autre matériel plomberie (à préciser)","GROSSE_FOURNITURE","u",1,"autre"],
  ["chauffage_ecs_autres_autre_mat_riel_chauffage_ecs_pr_ciser","Chauffage/ECS > Autres","Autre matériel chauffage/ECS (à préciser)","GROSSE_FOURNITURE","u",1,"autre"],
  ["clim_ventilation_autres_autre_mat_riel_clim_ventilation_pr_ciser","Clim/Ventilation > Autres","Autre matériel clim/ventilation (à préciser)","GROSSE_FOURNITURE","u",1,"autre"],
];

const CORRESPONDENCE_DATA = [
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","sanitaire_wc_petites_fournitures_pipe_wc_droite_100",100,"Raccords/Fixations",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","sanitaire_wc_petites_fournitures_robinet_d_arr_t_1_4_tour_12_17",100,"Raccords/Fixations",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","sanitaire_wc_petites_fournitures_flexible_alimentation_wc_12_17",100,"Raccords/Fixations",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","sanitaire_wc_petites_fournitures_kit_fixation_cuvette_vis_tiges_chevilles",100,"Raccords/Fixations",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","sanitaire_wc_petites_fournitures_joint_de_pipe_wc",100,"Raccords/Fixations",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","sanitaire_wc_petites_fournitures_joint_cuvette_wc",100,"Raccords/Fixations",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","sanitaire_wc_petites_fournitures_manchon_wc_100_110",60,"Étanchéité",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","fournitures_universel_tanch_it_silicone_sanitaire_anti_moisissure",60,"Étanchéité",1,"{}"],
  ["sanitaire_wc_pack_wc_pos_cuvette_r_servoir","fournitures_universel_tanch_it_ruban_ptfe_t_flon",60,"Étanchéité",1,"{}"],
  ["sanitaire_wc_wc_suspendu_cuvette_wc_suspendue","sanitaire_wc_wc_suspendu_b_ti_support_universel",100,"Indispensables",1,"{\"wc_type\":\"suspendu\"}"],
  ["sanitaire_wc_wc_suspendu_cuvette_wc_suspendue","sanitaire_wc_wc_suspendu_plaque_de_commande_double_touche",100,"Indispensables",1,"{\"wc_type\":\"suspendu\"}"],
  ["sanitaire_wc_wc_suspendu_cuvette_wc_suspendue","sanitaire_wc_petites_fournitures_kit_fixation_cuvette_vis_tiges_chevilles",100,"Indispensables",1,"{\"wc_type\":\"suspendu\"}"],
  ["sanitaire_wc_wc_suspendu_cuvette_wc_suspendue","sanitaire_wc_petites_fournitures_kit_isolation_phonique_wc_suspendu",60,"Options",1,"{\"wc_type\":\"suspendu\"}"],
  ["sanitaire_wc_wc_suspendu_cuvette_wc_suspendue","fournitures_universel_tanch_it_ruban_ptfe_t_flon",60,"Options",1,"{\"wc_type\":\"suspendu\"}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_lavabo","sanitaire_lavabo_vasque_vier_petites_fournitures_flexibles_alimentation_3_8_pair",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_lavabo","sanitaire_lavabo_vasque_vier_petites_fournitures_robinets_d_arr_t_1_4_tour_12_17",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_lavabo","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_lavabo","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_vier","sanitaire_lavabo_vasque_vier_petites_fournitures_flexibles_alimentation_3_8_pair",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_vier","sanitaire_lavabo_vasque_vier_petites_fournitures_robinets_d_arr_t_1_4_tour_12_17",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_vier","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_mitigeur_vier","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Raccords",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","sanitaire_lavabo_vasque_vier_petites_fournitures_siphon_vier_40_1_bac",100,"Évacuation",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","sanitaire_lavabo_vasque_vier_petites_fournitures_tube_pvc_vacuation_40_1_m",100,"Évacuation",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","sanitaire_lavabo_vasque_vier_petites_fournitures_coude_pvc_40_87",100,"Évacuation",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","sanitaire_lavabo_vasque_vier_petites_fournitures_manchon_pvc_40",100,"Évacuation",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","fournitures_universel_pvc_colle_pvc_pression_vacuation",60,"Consommables",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","fournitures_universel_pvc_d_capant_nettoyant_pvc",60,"Consommables",1,"{}"],
  ["sanitaire_lavabo_vasque_vier_vier_1_bac","fournitures_universel_tanch_it_silicone_sanitaire_anti_moisissure",60,"Consommables",1,"{}"],
  ["sanitaire_douche_baignoire_mitigeur_douche_mural","sanitaire_douche_baignoire_petites_fournitures_raccords_excentr_s_paire",100,"Raccords",1,"{}"],
  ["sanitaire_douche_baignoire_mitigeur_douche_mural","sanitaire_douche_baignoire_petites_fournitures_rosaces_paire",100,"Raccords",1,"{}"],
  ["sanitaire_douche_baignoire_mitigeur_douche_mural","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Raccords",1,"{}"],
  ["sanitaire_douche_baignoire_mitigeur_douche_mural","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Raccords",1,"{}"],
  ["sanitaire_douche_baignoire_colonne_de_douche","sanitaire_douche_baignoire_petites_fournitures_flexible_douche_inox_1_5m",60,"Compléments",1,"{}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_groupe_de_s_curit_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_siphon_groupe_de_s_curi",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_raccord_di_lectriqu",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","plomberie_alimentation_mesure_r_ducteur_de_pression_r_glable",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_50l","chauffage_ecs_eau_chaude_chauffe_eau_vase_d_expansion_sanitaire",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_groupe_de_s_curit_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_siphon_groupe_de_s_curi",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_raccord_di_lectriqu",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","plomberie_alimentation_mesure_r_ducteur_de_pression_r_glable",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_100l","chauffage_ecs_eau_chaude_chauffe_eau_vase_d_expansion_sanitaire",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_groupe_de_s_curit_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_siphon_groupe_de_s_curi",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_raccord_di_lectriqu",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","plomberie_alimentation_mesure_r_ducteur_de_pression_r_glable",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_150l","chauffage_ecs_eau_chaude_chauffe_eau_vase_d_expansion_sanitaire",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_groupe_de_s_curit_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_siphon_groupe_de_s_curi",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_raccord_di_lectriqu",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","plomberie_alimentation_mesure_r_ducteur_de_pression_r_glable",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_200l","chauffage_ecs_eau_chaude_chauffe_eau_vase_d_expansion_sanitaire",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_groupe_de_s_curit_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_siphon_groupe_de_s_curi",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_raccord_di_lectriqu",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","plomberie_alimentation_mesure_r_ducteur_de_pression_r_glable",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_lectrique_300l","chauffage_ecs_eau_chaude_chauffe_eau_vase_d_expansion_sanitaire",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_groupe_de_s_curit_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_siphon_groupe_de_s_curi",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","chauffage_ecs_eau_chaude_chauffe_eau_petites_fournitures_kit_raccord_di_lectriqu",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","plomberie_alimentation_vannes_vanne_d_arr_t_1_4_tour_20_27",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Indispensables",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","plomberie_alimentation_mesure_r_ducteur_de_pression_r_glable",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_eau_chaude_chauffe_eau_chauffe_eau_thermodynamique","chauffage_ecs_eau_chaude_chauffe_eau_vase_d_expansion_sanitaire",60,"Souvent",1,"{\"ecs\":true}"],
  ["chauffage_ecs_chauffage_radiateur_acier_panneau","chauffage_ecs_chauffage_petites_fournitures_robinet_thermostatique",100,"Raccordement",1,"{}"],
  ["chauffage_ecs_chauffage_radiateur_acier_panneau","chauffage_ecs_chauffage_petites_fournitures_t_de_r_glage",100,"Raccordement",1,"{}"],
  ["chauffage_ecs_chauffage_radiateur_acier_panneau","chauffage_ecs_chauffage_petites_fournitures_purgeur_radiateur",100,"Raccordement",1,"{}"],
  ["chauffage_ecs_chauffage_radiateur_acier_panneau","chauffage_ecs_chauffage_petites_fournitures_support_radiateur_kit",100,"Raccordement",1,"{}"],
  ["chauffage_ecs_chauffage_radiateur_acier_panneau","fournitures_universel_joints_joints_plats_fibre_assortis",100,"Raccordement",1,"{}"],
  ["chauffage_ecs_chauffage_radiateur_acier_panneau","fournitures_universel_tanch_it_ruban_ptfe_t_flon",100,"Raccordement",1,"{}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_petites_fournitures_support_mural_unit_ext_rieure",100,"Installation",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_petites_fournitures_plots_antivibratoires_lot",100,"Installation",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_petites_fournitures_liaison_frigorifique_cuivre_i",100,"Installation",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_petites_fournitures_goulotte_clim_accessoires",100,"Installation",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_petites_fournitures_tuyau_vacuation_condensats_m",100,"Installation",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_petites_fournitures_c_ble_lectrique_clim_m",100,"Installation",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_petites_fournitures_disjoncteur_d_di_clim",100,"Installation",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_consommables_azote_test_tanch_it",30,"Consommables",1,"{\"clim\":true}"],
  ["clim_ventilation_climatisation_kit_monosplit_complet","clim_ventilation_climatisation_consommables_nettoyant_changeur_spray",30,"Consommables",1,"{\"clim\":true}"],
  ["clim_ventilation_ventilation_vmc_vmc_simple_flux_groupe","clim_ventilation_ventilation_vmc_gaines_vmc_isol_es_m",100,"Réseau",1,"{\"vmc\":true}"],
  ["clim_ventilation_ventilation_vmc_vmc_simple_flux_groupe","clim_ventilation_ventilation_vmc_bouches_vmc_cuisine",100,"Réseau",1,"{\"vmc\":true}"],
  ["clim_ventilation_ventilation_vmc_vmc_simple_flux_groupe","clim_ventilation_ventilation_vmc_colliers_de_serrage_vmc",100,"Réseau",1,"{\"vmc\":true}"],
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // 1. Clear existing global data
    await supabase.from("material_correspondence").delete().not("id", "is", null);
    await supabase.from("catalog_material").delete().is("user_id", null);

    // 2. Insert catalog materials with slugs
    const slugToId = new Map<string, string>();
    const batchSize = 50;
    
    for (let i = 0; i < CATALOG_DATA.length; i += batchSize) {
      const batch = CATALOG_DATA.slice(i, i + batchSize).map(([slug, category_path, label, type, unit, default_qty, tags]) => ({
        slug,
        category_path,
        label,
        type,
        unit,
        default_qty: Number(default_qty),
        tags: [String(tags)],
        unit_price: 0,
        vat_rate: type === "GROSSE_FOURNITURE" ? 10 : 20,
      }));

      const { data, error } = await supabase.from("catalog_material").insert(batch).select("id, slug");
      if (error) {
        console.error("Catalog insert error:", error);
        throw error;
      }
      for (const row of data ?? []) {
        if (row.slug) slugToId.set(row.slug, row.id);
      }
    }

    console.log(`Inserted ${slugToId.size} catalog materials`);

    // 3. Insert correspondences
    const corrRows = [];
    let skipped = 0;
    for (const [sourceSlug, targetSlug, weight, group, defaultQty, conditionsJson] of CORRESPONDENCE_DATA) {
      const sourceId = slugToId.get(String(sourceSlug));
      const targetId = slugToId.get(String(targetSlug));
      if (!sourceId || !targetId) {
        skipped++;
        console.warn(`Skipping correspondence: ${sourceSlug} -> ${targetSlug} (missing ID)`);
        continue;
      }
      corrRows.push({
        source_material_id: sourceId,
        target_material_id: targetId,
        weight: Number(weight),
        group_label: String(group),
        default_qty: Number(defaultQty),
        conditions_json: JSON.parse(String(conditionsJson)),
      });
    }

    for (let i = 0; i < corrRows.length; i += batchSize) {
      const batch = corrRows.slice(i, i + batchSize);
      const { error } = await supabase.from("material_correspondence").insert(batch);
      if (error) {
        console.error("Correspondence insert error:", error);
        throw error;
      }
    }

    console.log(`Inserted ${corrRows.length} correspondences, skipped ${skipped}`);

    return new Response(JSON.stringify({
      success: true,
      catalog_count: slugToId.size,
      correspondence_count: corrRows.length,
      skipped,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Import error:", error);
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Unknown" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
